### ISSUE TITLE
[RFC] About the Rich Text Editor

### ISSUE THREAD

**Issue by SeanChao** [SEQAQ/qaq-react#13]
I've searched some open source projects:

[Draft.js](https://github.com/facebook/draft-js) A rich-text editor, as with [this markdown extension](https://github.com/Rosey/markdown-draft-js) to serialize/deserialize in to markdown

[rich-markdown-editor](https://github.com/outline/rich-markdown-editor) A rich-text editor with built-in markdown support, but the user cannot edit md source code

Which one to use? I suggest Draft.js because we can allow the user to edit raw md source code.

Relating to #6

**Comment by sdjn-wxy** [comment]
I prefer Draft.js as you have pointed out that it allows user to edit raw code, 

which provide more space for user to edit their questions and answers.

**Comment by SeanChao** [comment]
I'm working on building a markdown/richtext editor upon draft.js
